### ISSUE TITLE
[Misc] Identify and document post-deployment manual configurations for special SWB workspaces

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#19]
We need to identify and document all post-deployment manual configuration steps we have performed, especially for the special SWB workspaces, in order to re-create them after upgrade.

**Comment by aaronmbruce** [comment]
Most of these have been performed by @fergusonsha-umkc

**Comment by fergusonsha-umkc** [comment]
I think, instead of just documenting the post-deployment customizations made to the specialized workspaces, I'll actually update their templates to deploy them as tailored.  Everything I had done while things were still in development, is now ready for that, and I think we found a happy place with the SAS workspace storage setup, although I base that on not having heard of issues since the last adjustment, from Vasanthi who was testing the layout.  Further refinement can be done and then the template updated, as needed, too.

The CLAMP workspace was just post-modified to implement rclone mount, before I had it automated via template, and the SAS workspace much the same aside from the resource allocation adjustments and for balancing S3 and EBS storage utilization.

**Comment by fergusonsha-umkc** [comment]
Then, we would just diff and import them like we would our main, customized templates.

**Comment by fergusonsha-umkc** [comment]
As for other Service Workbench customizations, the approach I'm using for upgrading our SWB accounts, will preserve those since we're using the original archived codebase our environments were installed from and doing a "git pull" to merge to the latest version.  I can make note of any exceptions to this rule.
