### ISSUE TITLE
Testing SWB upgrade in Dev/Sandbox env

### ISSUE THREAD

**Issue by vasanthi014** [Missouri-BMI/service-workbench-on-aws#22]
Testing Report: 04/27/2022

1. Onboarding message and do we need to keep the "Cognito native pool" option? 
![image](https://user-images.githubusercontent.com/19035729/165589131-3f5eed06-9d80-4ef1-bfcb-04b7815fd793.png)

2. Sagemaker workspace via AppStream 2.0
- longer waiting time at every launch (not just the initial time)
![image](https://user-images.githubusercontent.com/19035729/165590827-bdbe46e9-ffe7-47f0-b2e1-efcce3e34159.png)
- freezes a lot (try `pip list`)
- can't do `pip install`

_Originally posted by @sxinger in https://github.com/Missouri-BMI/service-workbench-on-aws/issues/14#issuecomment-1111372873_

**Comment by sxinger** [comment]
3. default windows workspace via AppStream2.0
- longer waiting time at every launch (not just the initial time)
   -- 2 min to start AppStream and about 2 min to start RDP
   -- noticed that a slight delay with cursor movement
   -- freezes a lot more often 
- not able to copy & paste anything out of the RDP 
- can't do much useful testing without some of the customizations (e.g. R installed, ODBC connector, etc.)

**Comment by sxinger** [comment]
@fergusonsha-umkc I can already see the operational performance is getting impaired a lot with the AppStream2.0 being in the way... although there are some good features (e.g., no copy and paste is allowed out of RDP),... Is that what you have experienced? I think we will want to report this back to Travis before we move forward with the upgrade.

**Comment by sxinger** [comment]
4. default linux workspace via AppStream2.0
- longer waiting time at every launch (not just the initial time)
   -- 2 min to start AppStream and about 2 min to start RDP
   -- froze so often that i can barely go pass the SSH connection step.
- not able to copy & paste anything out of the RDP

**Comment by sxinger** [comment]
----------------------

From: Song, Xing 
Sent: Wednesday, April 27, 2022 3:23 PM
To: 'Berkley, Travis' <travberk@amazon.com>; znath <znath@amazon.com>
Cc: Ferguson, Shaun <fergusonsha@umkc.edu>; Bruce, Aaron <abruce@umkc.edu>; Mandhadi, Vasanthi (Medical Research Office) <mandhadiv@health.missouri.edu>
Subject: Initial test on upgraded SWB workspaces based on AppStream2.0 - RE: important security questions...
Importance: High

Hi, Travis, 

I finally got a chance to test out the upgraded SWB built on AppStream2.0. While I can see some good security features enabled by AppStream2.0, I can’t help noticing that the overall operationality has been impaired. I have tested out default SageMaker and Windows workspaces, which froze a lot more often than before and I can barely do anything there…  I’m wondering if that’s what’s supposed to happen or we are missing some configuration steps? With current experience, I think we will need to re-evaluate whether to do the upgrade at all……

Song

**Comment by fergusonsha-umkc** [comment]
Yes, I think we need to get time with Travis and have him experience what we're experiencing and let us know if perhaps there is some tuning that can be done (faster AppStream instances?) but some things like the Linux workspace connection process are just abysmal...

**Comment by fergusonsha-umkc** [comment]
Everything was baseline from their source repo in Sandbox, so things like the login page will retain our current customizations if/when we move forward into Dev and Prod.

**Comment by sxinger** [comment]
I have other priorities to focus on and didn't get a chance to follow up with Travis. @vasanthi014 can you help or delegate to someone who would have the bandwidth to reach out to Travis and Nathan for a 30-min meeting on "AppStream2.0 SWB Performance issue discussion"? My calendar is up to date.

**Comment by fergusonsha-umkc** [comment]
@vasanthi014 @sxinger I will follow up on our email thread discussing our concerns, to ask for the meeting.  Can our new Project Manager assist in arranging the calendar and Zoom pieces?

**Comment by fergusonsha-umkc** [comment]
Ferguson, Shaun
Wed 5/11/2022 3:20 PM
Hi Travis, Nathan,

We'd like to follow up on this information with a 30-minute Zoom with you both, to show you what the experience is like, or alternatively we can provision Sandbox SWB researcher accounts for you to test with and then we can discuss.  Since this is very non-production, and I set things up for minimal-cost or minimal-recommended, I am wondering if increasing resources on the AppStream instances (and providing larger workspace types to test with) might go to addressing some of the performance concerns Dr. Song raised, along with what you pointed out about setting up a (potentially filtered so not completely wide-open) NAT gateway for making outbound requests to do things like pip installs and other fundamentally necessary Internet connections from the private workspaces.

Vyshnavi, can you work with our calendars and the feedback we get from Travis and Nathan, to schedule this Zoom in the near future?  Much appreciated!

Sincerely,


Shaun Ferguson

Systems Administrator - Research

UMKC IS Foundation Services

**Comment by sxinger** [comment]
mark it as complete as the first round of testing was done.
