### ISSUE TITLE
Create two new resource accounts: Application-TRE-Dev, Application-TRE-Prod

### ISSUE THREAD

**Issue by vyshu1094** [Missouri-BMI/service-workbench-on-aws#24]

**Comment by fergusonsha-umkc** [comment]
I will freely admit that all of these master issues and nested sub-issues is beginning to confuse me about where I need to be recording my progress notes, because there is not as far as I know a "tree view" of these issues for me to review in context, only a flat view.  I'd therefore ask, please only assign me to one or the other, as appropriate for where you wish to have the context of work documented.  @vyshu1094 @vasanthi014 @sxinger @mosaa

If there is a more helpful manner to review the project trees and branches, that I've not found, please link me!

**Comment by fergusonsha-umkc** [comment]
Account email aliases requested, enrollment under Preparation OU to follow

**Comment by mosaa** [comment]
@fergusonsha-umkc: Please document in the specific ticket. Master issues are only created to track and understand all the things need to be done to accomplish a complex deliverable (only if it is a complex one).

**Comment by fergusonsha-umkc** [comment]
Sounds good thank you!

**Comment by fergusonsha-umkc** [comment]
These are now fully enrolled under our organization Control Tower, next steps are to get them opted into the AppStream 2.0 beta in us-east-2 through Travis.

**Comment by fergusonsha-umkc** [comment]
If you would like to close this out as complete, that's fine, it essentially is.  We'll not be using these accounts until we work on TRE SWB deployment next month, post-current-env-upgrade, and the first step in that will be getting the AppStream 2.0 service available in us-east-2 under these accounts if it is not still.
