### ISSUE TITLE
[Question] SWB stopped tab shows all of my workspaces having costs for yesterday

### ISSUE THREAD

**Issue by spinkac** [Missouri-BMI/service-workbench-on-aws#42]
@aaronmbruce @fergusonsha-umkc  When I logged into SWB this morning to start up one of my workspaces, I observed that every single one of my workspaces had cost for yesterday. Obviously, I was not using any of them, so if you were not using them either, then something odd is occurring. Thanks for looking into this!

**Comment by fergusonsha-umkc** [comment]
Yaswitha also reported this last week.  This is because we're now propagating billing tags to include the provisioned EBS storage and network interfaces associated with workspaces, which before we wrote a custom Lambda function to do it, was not getting included in the cost accrual calculation within SWB (and in the Cost Explorer reports tied to workspace/project).  EBS storage accrues for as long as it exists, and is not based on running status of the attached EC2 instance.

**Comment by vasanthi014** [comment]
Thank you @fergusonsha-umkc 

@soliman455 @kzraryan-mu fyi

**Comment by spinkac** [comment]
@fergusonsha-umkc So just having the space available costs around $1.41 per day? Good to know, thanks!

**Comment by fergusonsha-umkc** [comment]
Yep. Daily storage cost will be relative to the size of the standard disk provisioned, so will vary across different workspace types that have additional EBS disks, like the SAS workspaces vs the standard Windows spaces, or when we grow a disk after its been launched.  Also I'm working still on getting this implemented for Sagemaker workspaces too, which use a different API call, soon as I can.

**Comment by fergusonsha-umkc** [comment]
@Yaswitha-MU FYI, since I don't think I got back with you via email.

**Comment by Yaswitha-MU** [comment]
Thank You @fergusonsha-umkc
